### ISSUE TITLE
Trouble deserializing an array

### ISSUE THREAD

**Issue by omatrot** [Diademe/dcerialize#1]
Hi @PMDiademe.
I'm trying to deserialize a complex object array with circular references.

The code is like the following:

```
          RefCycleDetectionEnable();
          const datis: Vehicule[] = DeserializeArray(
            message.listDatiOfCompany,
            () => Vehicule
          );
          RefClean();
          RefCycleDetectionDisable();
```

It fails with the following error: 

```
  Message=Error: Expected input to be an array but received: object
  Source=
  StackTrace:
Error: Expected input to be an array but received: object
    at DeserializeArrayInternal (https://localhost:44338/src-app-components-dispositifsDATI-dispositifsDATI-module.js:441:15)
    at DeserializeInternal (https://localhost:44338/src-app-components-dispositifsDATI-dispositifsDATI-module.js:627:35)
    at DeserializeInternal (https://localhost:44338/src-app-components-dispositifsDATI-dispositifsDATI-module.js:636:35)
    at DeserializeInternal (https://localhost:44338/src-app-components-dispositifsDATI-dispositifsDATI-module.js:636:35)
    at DeserializeArrayInternal (https://localhost:44338/src-app-components-dispositifsDATI-dispositifsDATI-module.js:461:30)
    at Object.deserializationContinuation (https://localhost:44338/src-app-components-dispositifsDATI-dispositifsDATI-module.js:1620:20)
    at DeserializeArray (https://localhost:44338/src-app-components-dispositifsDATI-dispositifsDATI-module.js:769:20)
    at SafeSubscriber._next (https://localhost:44338/src-app-components-dispositifsDATI-dispositifsDATI-module.js:8016:98)
    at SafeSubscriber.__tryOrUnsub (https://localhost:44338/vendor.js:235125:16)
    at SafeSubscriber.next (https://localhost:44338/vendor.js:235064:22)

```

In the debugger, I can see that the last call to DeserializeArrayInternal receives null for the first parameter data, and undefined for the target parmeter, The code throws because data is not an array.

I'm looking for guidance on how to troubleshoort the problem.

What can be the cause of the problem? A discrepencies between the typescript class and the c# class regarding serialization?

Thansks for your help.

**Comment by omatrot** [comment]
Ok, I have overcomed this problem configuring the JSonSerializer to ignore null reference.

Now I have another problem where references are not found on the current objet, which is common when you deserialize an array where the object is not in the current object tree.

"Reference found before its definition"

```
 deserializationGetObject(json) {
        if (json.hasOwnProperty("$ref")) {
            const ref = parseInt(json.$ref, 10);
            if (!this.cycle.ref2obj.has(ref)) {
                throw new Error("Reference found before its definition");
            }
            return this.cycle.ref2obj.get(ref);
        }
        return undefined;
    }
```

**Comment by PMDiademe** [comment]
Hi,
I tried the following code, and it works:
```typescript
class Vehicule {
    @autoserializeAs(() => Vehicule)
    public other: Vehicule;
}
const v1 = new Vehicule();
const v2 = new Vehicule();
v1.other = v2;
v2.other = v1;
// serialized
RefCycleDetectionEnable();
const list = SerializeArray([v1, v2], () => Vehicule);
const stringList = JSON.stringify(list); // "[{"$id":"1","other":{"$id":"2","other":{"$ref":"1"}}},{"$ref":"2"}]"

// deserialize
const jsonList = JSON.parse(stringList);
const deserializedList: Vehicule[] = DeserializeArray(
    jsonList,
    () => Vehicule
);
RefClean();
RefCycleDetectionDisable();

// assert
const itIsTrue = deserializedList[0].other === deserializedList[1]; // true
```

If you need more help, I will need an example with the class definition (with its dcerialize decorators), and the string you need to de-serialize.

**Comment by omatrot** [comment]
I'll try to provide you with elements tomorrow morning.
Thanks.

**Comment by omatrot** [comment]
As requested, attached is a zip file containing all the entities. Only those of interest right now are annotated with **dcerialize** decorators. I'm waiting to understand exactly how this will work with this first sample to generalize the annotations on all entities.

The code uses another third party module to track local changes, before sending them back to the server. You'll have to npm/yarn install '**trackable-entities**' as well as **dcerialize**.

The json file is the payload (an array with 6 elements) received from the server to be deserialized with the following code:

RefCycleDetectionEnable();
          const datis: Vehicule[] = DeserializeArray(
            message.listDatiOfCompany,
            () => Vehicule
          );
          RefClean();
          RefCycleDetectionDisable();

I have confirmed that if the array contains only one root object, there is no reference problem because everything is there in this signtl graph. With several objects, references may be spread anywhere in the objetc graphs.

Hope that helps.

Kind regards.

[Models.zip](https://github.com/Diademe/dcerialize/files/3582498/Models.zip)
[ArrayOfVehicule.jsonstring.txt](https://github.com/Diademe/dcerialize/files/3582499/ArrayOfVehicule.jsonstring.txt)

**Comment by PMDiademe** [comment]
I looked into your files, and found a reason for the error I was able to reproduce.
In the file `VehiculeGpsBoxInfo.ts`, you have to uncomment the following lines:
```typescript
  //@autoserializeAs(() => Vehicule)
  //vehicule: Vehicule;
```
If you don't, the serializer will drop the object (I will call it `O`) define at the path `[0].vehiculeGpsBoxInfo.vehiculeConfigurationNavigation.vehiculeGpsBoxInfoVehiculeConfigurationNavigation[1]` of your file `ArrayOfVehicule.jsonstring.txt`. The definition of the object referenced by "13" is inside `O`. It appears at this path `[0].vehiculeGpsBoxInfo.vehiculeConfigurationNavigation.vehiculeGpsBoxInfoVehiculeConfigurationNavigation[1].vehicule.fleetDetail[0].fleet.fleetDetailFleet[0]` of your file `ArrayOfVehicule.jsonstring.txt`. So the serializer will not save this object in its dictionary of references.
Then, it will continue to parse the input and find a "$ref": "13" (in `[0].fleetDetail[3]` of your file `ArrayOfVehicule.jsonstring.txt`), it will look in its dictionary of references, and throw an exception since it doesn't have a definition associated to "13".

**Comment by omatrot** [comment]
Thanks for that, I commented out these lines because I thought it was not sent by the server. I'll keep you updated next Wednesday.




Télécharger Outlook pour Android







On Fri, Sep 6, 2019 at 5:01 PM +0200, "Pierre MACHEREL" <notifications@github.com> wrote:












I looked into your files, and found a reason for the error I was able to reproduce.

In the file VehiculeGpsBoxInfo.ts, you have to uncomment the following lines:
  //@autoserializeAs(() => Vehicule)
  //vehicule: Vehicule;


If you don't, the serializer will drop the object (I will call it O) define at the path [0].vehiculeGpsBoxInfo.vehiculeConfigurationNavigation.vehiculeGpsBoxInfoVehiculeConfigurationNavigation[1] of your file ArrayOfVehicule.jsonstring.txt. The definition of the object referenced by "13" is inside O. It appears at this path [0].vehiculeGpsBoxInfo.vehiculeConfigurationNavigation.vehiculeGpsBoxInfoVehiculeConfigurationNavigation[1].vehicule.fleetDetail[0].fleet.fleetDetailFleet[0] of your file ArrayOfVehicule.jsonstring.txt. So the serializer will not save this object in its dictionary of references.

Then, it will continue to parse the input and find a "$ref": "13" (in [0].fleetDetail[3] of your file ArrayOfVehicule.jsonstring.txt), it will look in its dictionary of references, and throw an exception since it doesn't have a definition associated to "13".

**Comment by omatrot** [comment]
Yep that was it !
Works perfectly now.
Thanks for that.

**Comment by omatrot** [comment]
Hi @PMDiademe,

I'm facing a new issue of type "Reference found before its definition" regarding deserializing an array.
This time $id11 is not seen before being used...

If I urderstood you correctly the last time, it was because the property and serialization attribute were missing in the object.

This time, it seems that this is OK though.

In the JON file, I have the following reference:

```
                     "gpsBoxTypeNavigation":{
                        "$id":"11",

```
The containing object is of type Vehicule and has the property attributed correctly:

```
  @autoserializeAs(() => GpsBoxType)
  gpsBoxTypeNavigation: GpsBoxType;

```

I do not understand why it is not seen by the deserializer.

Attached is the JSON file and the typescript classes.

Thanks for your help.

[dcerialize_Reference found before its definition_$ref11.txt](https://github.com/Diademe/dcerialize/files/3652940/dcerialize_Reference.found.before.its.definition_.ref11.txt)

**Comment by PierreMacherel** [comment]
(I am @PMDiademe)
I can't reproduce your bug: 
```typescript
DeserializeArray(blop, () => Vehicule);
```
runs fine (no exception raised).
For further help, it would spare me a lot of time if you could create a repository so that I could clone it, with detailed the steps to reproduce your problem. I only need the client side (you can hard code the server answer in a variable).

**Comment by omatrot** [comment]
@PMDiademe I'll create this repo next Wednesday.
Thanks in advance.

**Comment by omatrot** [comment]
Here is the Repo invitation [link](https://github.com/omatrot/dcerialize-issue-1/invitations).
You should just be able to start debugging in VS Code
Thanks in advance.

**Comment by PierreMacherel** [comment]
OK, I found the issue. The files `dcerialize_Reference found before its definition_$ref11.txt` and the `json` variable in the file `dcerialize-issue#1.ts` in your repo are not the equal.

The Json object being deserialized may not be read from top to bottom. It is read in the order in which the decorators are read ([Decorator Evaluation](https://www.typescriptlang.org/docs/handbook/decorators.html#decorator-evaluation)).


for instance:
```typescript
class Bar {
    @autoserializeAs(() => Number)
    val: number;
    constructor(val: number) {
        this.val = val;
    }
}

class Foo {
    @autoserializeAs(() => Bar)
    a;
    @autoserializeAs(() => Bar)
    b;
}
const fooInstance = new Foo();
fooInstance.a = new Bar(1);
fooInstance.b = fooInstance.a;
RefCycleDetectionEnable();

// correctJson = { "$id": "1", "a": { "$id": "2", "val": 1 }, "b": { "$ref": "2" } }
const correctJson = Serialize(fooInstance, () => Foo);

// json send by the server
const incorectJSON =  { "$id": "1", "a": { "$ref": "2" }, "b": { "$id": "2", "val": 1 }};
// or const incorectJSON =  { "$id": "1", "b": { "$id": "2", "val": 1 }, "a": { "$ref": "2" }};
Deserialize(incorectJSON, () => Foo); // Error: Reference found before its definition
```
The order of property in the JSON sent by the server doesn't matter:
`Deserialize` expect a Foo. It loads the annotation gathered by the decorators in the order of the decorators i.e. "a", then "b" (top to bottom for members inside a class).
`incorectJSON["a"] = { "$ref": "2" }` is deserilized before ` { "$id": "2", "val": 1 }` being read.


For order of serialization with inheritance, [see the documentation](https://github.com/Diademe/dcerialize#order-of-serialization)

**Comment by omatrot** [comment]
> The order of property in the JSON sent by the server doesn't matter

I'm pretty sure the Serializer server side is not always consistent with the order of what is sent. It depends on the data. I had the same problem today just by having additional data in the database result later serialized.

It seems to me that the order is important.

Am I wrong?

How can I ensure that it works all the time whatever the data coming in?

**Comment by PierreMacherel** [comment]
You are correct, the order does matter. Dcerialize expects to read `$id: x` before reading `$ref: x`. The json sent by the server is a tree. Dcerialize will traverse this tree in its own way, but the property *id before ref* must be true. My point was that the order of the traversal of dcerialize is deterministic.

In your case, if you use newtonesoft, you have to ensure that it produces the good tree. Newtonsoft creates `$id` the first time it encounters the object, so you should have the same member ordering for typescript classes and c# classes.

A better solution would be to do 2 phases during the deserialization : collect the ids, then do the proper deserialization. It should be done carefully to avoid deserializing twice the same object (with potential side effect that could be caused). I could do it, but I have ongoing modifications to complete before.

**Comment by omatrot** [comment]
For now I'll put attributes on properties server side to garantee the order of serialization.
Because the generator is the same for server and client, this should be consistent.
I'll get back to you with the outcome.

**Comment by omatrot** [comment]
Still having the same error after ordering properties on server during serialization.
I don't know if this is the same issue but in this case, this is a circular reference

```
"vehiculeConfigurationNavigation":{
                                             "$id":"22",
                                             ...
                                             "vehiculeGpsBoxInfoVehiculeConfigurationNavigation":[
                                                {
                                                    "$id":"23",
                                                   ...
                                                   "vehiculeConfigurationNavigation":{
                                                      "$ref":"22"
                                                   }
```

the parser seems to be actually parsing object with $id 22 that is referenced later in a nested object.

What do you think?

The issue repo is up to date with this case.

Anyways, I you think your 2 phases deserialization will be ready in a couple of month, I think I can wait.

**Comment by PierreMacherel** [comment]
In your json object, the `"$id":"22"` is at the given path (I use the vscode plugin jsonPath to extract it):
```javascript
[0].device.registration.company.fleet[0].fleetDetailFleet[1].vehicule.gpsBoxTypeNavigation.vehicule[2].vehiculeGpsBoxInfo.vehiculeConfigurationNavigation.$id
```
And dcerialize follow this path when the exception is raised:
```javascript
[0].device.registration.company.fleet[0].fleetDetailFleet[1].vehicule.gpsBoxTypeNavigation.gpsBoxConfiguration[0].$ref22
```
Those two paths differ after
```javascript
[0].device.registration.company.fleet[0].fleetDetailFleet[1].vehicule.gpsBoxTypeNavigation
```
`gpsBoxTypeNavigation` is of type `GpsBoxType`. In this class, `gpsBoxConfiguration` is before `vehicule`. That is why dcerialize raises an exception: it did not deserialized vehicule yet. I guess that in the server class `GpsBoxType`, `vehicule` is before `gpsBoxConfiguration`.

To get the second path, break when the exception is raised. Then look at the call stack, one set after 'deserializationContinuation'.
Step 1 `DeserializeArrayInternal`, look at the value of `(offset + i)` -> **[0]** (first part of the second path)
Step 2 `DeserializeInternal`, look at the value of `keyName` -> **device** (second part of the second path)
Step 3 `DeserializeInternal`, look at the value of `keyName` -> **registration** (third part of the second path)
...

**Comment by omatrot** [comment]
Ok shoot! The attribute [JsonProperty(Order = 9)] was missing server side on the Vehicule property in class GPSBoxType which explains why is it not in the correct order when sent to the client.
Thanks for your help, I think I'm close to make it work.

**Comment by omatrot** [comment]
This works perfectly now.
Thank you so much for the awesome work.
